version: '3.12'

services:
  web:
    build: ./VKR_landscape_design
    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/main
    ports:
      - 8000:8000

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: geo
      POSTGRES_PASSWORD: test
      POSTGRES_DB: olms_geo
    ports:
      - "6000:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U geo -d olms_geo']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
#    Для локального запуска, чтобы БД оставалась в том же состоянии
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

