"""create_recommendation_feedback_table

Revision ID: aea14e5a121c
Revises: 
Create Date: 2026-05-20 13:42:33.393984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aea14e5a121c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_feedback',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('point_x', sa.Double(), nullable=False),
    sa.Column('point_y', sa.Double(), nullable=False),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('territory_id', sa.Integer(), nullable=False),
    sa.Column('landscape_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=False),
    sa.Column('model_score', sa.Double(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 10', name='ck_recommendation_feedback_rating_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index('idx_feedback_rated', 'recommendation_feedback', ['rated_at'], unique=False)
    op.create_index('idx_feedback_territory_id', 'recommendation_feedback', ['territory_id'], unique=False)
    op.create_index('idx_feedback_territory_task', 'recommendation_feedback', ['territory_id', 'task_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_feedback_territory_task', table_name='recommendation_feedback')
    op.drop_index('idx_feedback_territory_id', table_name='recommendation_feedback')
    op.drop_index('idx_feedback_rated', table_name='recommendation_feedback')
    op.drop_table('recommendation_feedback')
    # ### end Alembic commands ###
